---
resources:
    - name: haraka-boshrelease
      type: git
      source:
          uri: https://github.com/finkit/haraka-boshrelease.git
          branch: master
    - name: bbl-bosh
      type: git
      source:
          uri: https://github.com/dazjones/bbl-bosh
          branch: master

jobs:
    - name: job-haraka-boshrelease
      public: true
      plan:
          - get: bbl-bosh
          - get: haraka-boshrelease
          - task: run
            config:
                platform: linux
                image_resource:
                    type: docker-image
                    source: {repository: darrenjones/docker-bbl}
                params:
                    GCP_PROJECT: default
                inputs:
                    - name: bbl-bosh
                run:
                    path: sh
                    args: 
                        - -exc
                        - |
                            cd bbl-bosh
                            printenv
                            ./create-bbl-env.sh
